version: '3.9'

services:
  next:
    build:
      context: ..
      dockerfile: .docker/dev.Dockerfile
    volumes:
      - ../.:/app
      - nextmods:/app/node_modules
    ports:
      - 8080:3000
      - 9230:9229
    restart: unless-stopped

volumes:
  nextmods:
